require('./routes/airports.routes')
require('./database')
const express = require('express')
const app = express()
const airportRoutes=require('./routes/airports.routes')
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/airports',airportRoutes)
app.listen(3000, () => {
  console.log('server started at 3000')
})
